name: The Lix Installer

branding:
  icon: "code"
  color: "gray-dark"

description: "Install Lix with the Lix Installer. See: https://git.lix.systems/lix-project/lix-installer"

runs:
  using: "composite"

  steps:
    # - if: runner.os == 'Linux' && runner.arch == 'X64'
    #   shell: bash
    #   run: echo "NIX_SYSTEM=x86_64-linux" >> $GITHUB_ENV

    # - if: runner.os == 'Linux' && runner.arch == 'ARM64'
    #   shell: bash
    #   run: echo "NIX_SYSTEM=aarch64-linux" >> $GITHUB_ENV

    # - if: runner.os == 'macOS' && runner.arch == 'X64'
    #   shell: bash
    #   run: echo "NIX_SYSTEM=x86_64-darwin" >> $GITHUB_ENV

    # - if: runner.os == 'macOS' && runner.arch == 'ARM64'
    #   shell: bash
    #   run: echo "NIX_SYSTEM=aarch64-darwin" >> $GITHUB_ENV

    # - uses: DeterminateSystems/nix-installer-action@v16
    #   with:
    #     source-url: https://install.lix.systems/lix/lix-installer-${{ env.NIX_SYSTEM }}
    #     diagnostic-endpoint: ""
    #     extra-conf: |
    #       experimental-features = nix-command flakes pipe-operator auto-allocate-uids
    #       auto-optimise-store = true
    #       auto-allocate-uids = true
    - uses: canidae-solutions/lix-quick-install-action@19e34da3031ec7e35f06561e3606c512a164c9aa # v2
      with:
        lix_conf: |
          experimental-features = nix-command flakes pipe-operator auto-allocate-uids
          auto-optimise-store = true
          auto-allocate-uids = true

    - name: Set up Lix cache
      uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
      with:
        diagnostic-endpoint: ""
