name: The Lix Installer

branding:
  icon: "code"
  color: "gray-dark"

description: "Install Lix with the Lix Installer. See: https://git.lix.systems/lix-project/lix-installer"

runs:
  using: "composite"

  steps:
    - if: runner.os == 'Linux' && runner.arch == 'X64'
      shell: bash
      run: echo "NIX_SYSTEM=x86_64-linux" >> $GITHUB_ENV

    - if: runner.os == 'Linux' && runner.arch == 'ARM64'
      shell: bash
      run: echo "NIX_SYSTEM=aarch64-linux" >> $GITHUB_ENV

    - if: runner.os == 'macOS' && runner.arch == 'X64'
      shell: bash
      run: echo "NIX_SYSTEM=x86_64-darwin" >> $GITHUB_ENV

    - if: runner.os == 'macOS' && runner.arch == 'ARM64'
      shell: bash
      run: echo "NIX_SYSTEM=aarch64-darwin" >> $GITHUB_ENV

    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      with:
        source-url: https://install.lix.systems/lix/lix-installer-${{ env.NIX_SYSTEM }}
        diagnostic-endpoint: ""
        extra-conf: |
          experimental-features = nix-command flakes pipe-operator auto-allocate-uids
          auto-optimise-store = true
          auto-allocate-uids = true

    - name: Set up Lix cache
      uses: DeterminateSystems/magic-nix-cache-action@def9f5a5c6a6b8751c0534e8813a5d0ad2635660 # v11
      with:
        diagnostic-endpoint: ""
